config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'menu#show'
  get  '/help',    to: 'menu#help'
  get  '/about',    to: 'menu#about'
  get  '/contact',    to: 'menu#contact'
  get  '/store',    to: 'menu#store'
  get  '/history',    to: 'menu#history'
  get  '/sign_up',  to: 'users#new'
  post '/sign_up',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :posts
  resources :account_activations, only: [:edit]
  default_url_options :host => "54.214.109.30"
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts,          only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<!-- footer -->
<div class="container">
  <footer class="footer">
    <small>
      The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "Facebook",   '#' %></li>
        <li><%= link_to "Zalo", '#' %></li>
        <li><%= link_to "Gmail", '#' %></li>
        <li><a href="http://news.railstutorial.org/">News</a></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_header.html.erb
    <!-- header -->
    <header>
      <nav class="navbar fixed-top navbar-light" style="background-color: teal;">
        <div class="container">
          <div class="logo-item">
            <%= content_tag(:i, "3d_rotation", class: "material-icons") %>
          </div>
          <div class="fix-logo">
            <%= link_to "DESIGN", root_path, id: "logo", class: "navbar-brand", data: {turbolinks: false}%>
            <span class="fix-span-title"> Photo for everyone</span>
          </div>
          <div class="blog-header-nav">
            <%= link_to "Colections", '#', class: "navbar-brand", style: "padding-top: 17px;", data: {turbolinks: false}%>
            <%= link_to "Explore", '#', class: "navbar-brand", style: "padding-top: 17px;", data: {turbolinks: false}%>
            <div class="dropdown">
              <button class="btn bmd-btn-icon dropdown-toggle" type="button" id="ex1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= content_tag(:i, "more_vert", class: "material-icons", style: "color: white") %>
              </button>
              <div class="dropdown-menu dropdown-menu-left" aria-labelledby="ex1">
                <%= link_to "About", about_path, class: "dropdown-item", data: {turbolinks: false}%>
                <%= link_to "Contact", contact_path, class: "dropdown-item", data: {turbolinks: false}%>
                <%= link_to "Store", store_path, class: "dropdown-item", data: {turbolinks: false}%>
                <%= link_to "History", history_path, class: "dropdown-item", data: {turbolinks: false}%>
                <%= link_to "Help", help_path, class: "dropdown-item", data: {turbolinks: false}%>
              </div>
            </div>
          </div>
          <div>
            <form class="form-inline my-2 my-lg-0">
              <% if logged_in? %>
                <%= link_to "Users", users_path, class: "navbar-brand", style: "padding-top: 17px;", data: {turbolinks: false}%>
                <div class="dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Account
                    </button>
                  <div class="dropdown-menu dropdown-menu-left" aria-labelledby="ex1">
                    <%= link_to "Profile", current_user, class: "dropdown-item", data: {turbolinks: false} %>
                    <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item", data: {turbolinks: false}%>
                    <div class="dropdown-divider"></div>
                    <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item", data: {turbolinks: false}%>
                  </div>
                </div>
              <% else %>
                <%= link_to "Login", login_path, class: "navbar-brand", style: "padding-top: 17px;", data: {turbolinks: false}%>
                <%= link_to "Sign up now !", sign_up_path, class: "btn btn-outline-danger", style: "color: white;", data: {turbolinks: false}%>
                <% end %>
              <fieldset disabled>
                <button type="button" class="btn btn-raised btn-secondary">Submit photo</button>
              </fieldset>
            </form>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Material Design for Bootstrap fonts and icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">

    <!-- Material Design for Bootstrap CSS -->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">

    <title>Design App | by: Trung Tran</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}", style: "text-align: center;") %>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
    <script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>
  </body>
</html>